### ISSUE TITLE
Rocks fails to connect to Azure XP Single

### ISSUE THREAD

**Issue by shyameg** [JakobChristensen/Sitecore.Rocks#74] opened 2018-04-18 07:43 UTC
I am unable to connect to Azure Sitecore XP Single after following the steps to install the rocks extensions in Visual Studio 2017 local machine. Later copied certain files to the folders in Sitecore\Shell\WebService and Sitecore\bin of Azure App Service dedicated for XP Single.

I get this message when I click the test button of Sitecore Rocks to configure the connection with Azure XP Single.

"An error occurred while making the HTTP request to https://sitecore-NNNNNN-single.azurewebsites.net/sitecore/shell/webservice/service2.asmx. This could be due to the fact that the server certificate is not configured properly with HTTP.SYS in the HTTPS case. This could also be caused by a mismatch of the security binding between the client and the server."

Any ideas or thoughts, the web.config file has been updated with the path to allow anonymous access. Also, I checked the appservice allows TLS1.0 and higher. The only gap I see is a X.509 certificate installation. Has anyone tried this scenario and your thoughts. 

This is a blocker for Azure integration development

**Comment by nickwesselman** [comment] 2018-11-02 20:37
I was able to successfully connect to an Azure XP0 instance using the following steps:

1. Fetch the Hard Rock Service Update Package and Sitecore Rocks VSIX for the [latest Rocks development build](https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/artifacts)
1. Deploy an XP0 instance via the Azure Portal
1. Install the Hard Rocks service using the Update Center and provided update package
1. Wait for Sitecore to restart after update package install
1. Add connection in Rocks using the full https URL of the instance (`https://[instance name].azurewebsites.net`)

Can you attempt to connect using the latest Hard Rock update package and Sitecore Rocks VSIX? These will be released shortly after Sitecore 9.1 GA (still compatible with 8.2+). If still having issues, is there something non-default about your installation or SSL configuration?

**Comment by nickwesselman** [comment] 2018-11-28 15:50
Have been unable to reproduce this, please attempt with 2.1.126 release and reopen if needed.

**Closed by nickwesselman** 2018-11-28 15:50 UTC
