### ISSUE TITLE
Anti package ignores items/templates that has or is a dependency on other items/templates in the same package

### ISSUE THREAD

**Issue by sud33p** [JakobChristensen/Sitecore.Rocks#56] opened 2017-08-09 02:29 UTC
On my attempt to create uninstallers, I've found that Anti package will miss to include items for removal in the `<uninstall><items>` section if:
- the item is used/referred by another item in the same package
- the item is referring to another item in the same package

Looks like the second condition is a repercussion of the first one, where if it can't include the first item that is being referred by the second one, it will miss to include the second item as well.

For e.g. if a package has the following templates:
- TemplateA
- TemplateB
If `TemplateB` has `TemplateA` as a base template, both will be excluded from the generated anti package.

This issue was discovered while trying to create an anti package for `Web Forms For Marketers 8.1 Initial Version`. The generated anti-package failed to remove a number of items that was installed from the WFFM package. 

Please let me know if you need more info.

**Comment by JakobChristensen** [comment] 2017-08-15 10:22
I think this was caused by having Template A and Template B on the same level - only Template A would be removed by the Anti package.

This should be fixed now.

**Closed by JakobChristensen** 2017-08-15 10:22 UTC
