### ISSUE TITLE
Date fields in VS Dark Theme

### ISSUE THREAD

**Issue by andrewvieau** [JakobChristensen/Sitecore.Rocks#16] opened 2016-05-24 16:34 UTC
Date Fields do not display properly in High Contrast mode in Visual Studio. The text is blank - you can't see the date that is selected until you click the date picker.

**Comment by JakobChristensen** [comment] 2016-06-09 13:00
Hmm... I am not able to reproduce this. It looks like this on my screen in High Contract.

![image](https://cloud.githubusercontent.com/assets/2310296/15930376/ea92b618-2e52-11e6-9306-30cc0fa01943.png)

**Comment by nickwesselman** [comment] 2018-10-29 17:53
I am also unable to reproduce. @andrewvieau if you are still experiencing this issue and have repro steps, please feel free to reopen.

**Comment by andrewvieau** [comment] 2018-10-29 18:35
I was wrong, this wasn't about High Contrast mode, it's Visual Studio's Dark theme.  See below.  Updated subject.

![10-29-2018 1-31-50 pm](https://user-images.githubusercontent.com/2454839/47672226-6fee0700-db7f-11e8-814f-827629fcdbd1.png)
![10-29-2018 1-32-05 pm](https://user-images.githubusercontent.com/2454839/47672227-6fee0700-db7f-11e8-996e-6725d8877183.png)
![10-29-2018 1-32-25 pm](https://user-images.githubusercontent.com/2454839/47672228-70869d80-db7f-11e8-9471-60acce673489.png)

**Comment by nickwesselman** [comment] 2018-10-30 17:21
I work in the Dark theme and this actually looks OK, what are you expecting to be different?

Empty field:
![image](https://user-images.githubusercontent.com/27013789/47737155-9d51b800-dc46-11e8-9c1f-090a793ea9ed.png)

Date selected:
![image](https://user-images.githubusercontent.com/27013789/47737183-ac386a80-dc46-11e8-9407-dfddbb928462.png)

**Comment by andrewvieau** [comment] 2018-10-30 19:15
You are looking at a Datetime field, which apparently displays fine (just checked it on my instance as well).  There is also a field type of Date.  Same raw value, but with a Date field the timestamp is always zeroes.  The selector in Rocks is slightly different as well - you have arrows, my icon looks more like a calendar.

In all of my screenshots, the value for the field is set, but you can't see anything unless you click to expand the calendar.  In my second screenshot, you can see that the value is highlighted, but you can't see anything.

The date field does not appear to be deprecated, but if it is then I'll just use Datetime from now on.

**Comment by nickwesselman** [comment] 2018-10-30 20:28
Got it, `Date` field vs `Datetime` was the missing link. Reproducing, will try to fix for the next release.

**Comment by nickwesselman** [comment] 2018-10-31 16:12
Latest pre-release build should solve this:
https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/artifacts

**Comment by nickwesselman** [comment] 2018-11-28 15:49
This is resolved in the 2.1.126 release.

**Closed by nickwesselman** 2018-11-28 15:49 UTC
