### ISSUE TITLE
Can't upload media to newly created media folder

### ISSUE THREAD

**Issue by cjaube** [JakobChristensen/Sitecore.Rocks#43] opened 2017-03-30 13:12 UTC
I created a "New Media Folder" and named it. Then I right clicked and selected "Upload Media" and selected an image. I received an "Item not found" exception stating that it could not find "New Folder". I was able to work around the issue by running a refresh on the Sitecore Explorer.

Sitecore Rocks, Version 2.0.54

**Comment by JakobChristensen** [comment] 2017-03-30 18:15
This was caused by not updating the item path when renaming an item.

This is fixed now.

**Closed by JakobChristensen** 2017-03-30 18:15 UTC
