### ISSUE TITLE
No Service Error on 8.2 Update-3 Site

### ISSUE THREAD

**Issue by clickatwill** [JakobChristensen/Sitecore.Rocks#46] opened 2017-04-17 23:47 UTC
Attempting to set up a new connection to an 8.2 Update-3 site, I'm getting a No Service error or if I just click Test, I get the following error-

> System.Web.Services.Protocols.SoapException: Server was unable to process request. ---> System.Exception: Cannot load provider. Base type is 'Sitecore.Security.Authentication.AuthenticationProvider'
>    at Sitecore.Configuration.ProviderHelper`2.ReadProviders()
>    at Sitecore.Configuration.ProviderHelper`2.get_Provider()
>    at Sitecore.Security.Authentication.DefaultAuthenticationManager.GetUserName(String rawUserName)
>    at Sitecore.Security.Authentication.DefaultAuthenticationManager.Login(String userName, String password, Boolean persistent)
>    at Sitecore.Visual.Service2.Login(Credentials credentials)
>    --- End of inner exception stack trace ---

I just installed the latest version of Rocks - 2.0.61 - as I was getting similar errors on prior versions.

**Comment by JakobChristensen** [comment] 2017-04-18 07:01
I cannot reproduce this.

I installed a clean 8.2 update 3 using SIM.
I opened the New Connection dialog in Rocks and entered host name and path, and clicked Test. 
Rocks asks to install Server Components which it should.
Rocks shows "Yes, it works"

Please check the the Sitecore.Rocks.Server assembly is in the /bin folder and that the service2.asmx file is in the /sitecore/shell/WebService foilder.

And please check if your solution has custom authentication handling.

**Comment by JakobChristensen** [comment] 2017-05-01 12:07
Closing this because of no reply.

**Closed by JakobChristensen** 2017-05-01 12:07 UTC
