### ISSUE TITLE
A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.

### ISSUE THREAD

**Issue by lobrien2886** [JakobChristensen/Sitecore.Rocks#21] opened 2016-07-20 13:46 UTC
Hi I get this error whenever I try to enter preview mode:

A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.UriFormatException: A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.

Source Error: 

Line 35:     args1.StartUrl = redirect;
Line 36: 
Line 37:     Sitecore.Pipelines.Pipeline.Start("loggingin", args1);
Line 38:     if (!args1.Success)
Line 39:     {

Source File: c:\inetpub\wwwroot\trainsite\Website\sitecore\shell\WebService\Browse.aspx    Line: 37 

Stack Trace: 

[UriFormatException: A relative URI cannot be created because the 'uriString' parameter represents an absolute URI.]
   System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind) +8458893
   Sitecore.Pipelines.LoggingIn.CheckStartUrl.GetLocalPath(String itemPath) +45
   Sitecore.Pipelines.LoggingIn.CheckStartUrl.ValidateStartUrl(LoggingInArgs args) +81
   Sitecore.Pipelines.LoggingIn.CheckStartUrl.Process(LoggingInArgs args) +72

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
   Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) +89
   Sitecore.Nexus.Pipelines.NexusPipelineApi.Resume(PipelineArgs args, Pipeline pipeline) +316
   Sitecore.Pipelines.Pipeline.Start(PipelineArgs args, Boolean atomic) +176
   Sitecore.Pipelines.Pipeline.Start(String pipelineName, PipelineArgs args, Boolean atomic) +89
   ASP.sitecore_shell_webservice_browse_aspx.__Render__control1(HtmlTextWriter __w, Control parameterContainer) in c:\inetpub\wwwroot\trainsite\Website\sitecore\shell\WebService\Browse.aspx:37
   System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children) +263
   System.Web.UI.Page.Render(HtmlTextWriter writer) +39
   System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +80
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +8921

**Comment by JakobChristensen** [comment] 2016-07-21 07:13
Hi lobrien2886

I think I have seen this before...

What version of the CMS are you using?
What is the host name of the connection (including protocol and port)?

**Comment by lobrien2886** [comment] 2016-07-21 19:37
Hi JakobChristensen

I think I found it. For whatever reason I have to leave a tab open in chrome that is signed into the admin account. I was doing this over the localhost and using Sitecore 8

**Comment by JakobChristensen** [comment] 2016-07-22 10:28
Hmm.. that bypasses the login process which is causing the issue.

But it is a work-around.

Let me test this on Monday...

**Comment by JakobChristensen** [comment] 2016-07-25 06:50
Well, I can't reproduce the issue.

I am on CMS 8.1.160321, and I tried the following combinations of hosts:
localhost
localhost:81
http://localhost
http://localhost:81

All are working (on my machine).

What specific version of the CMS, are you using?
Which version of Sitecore Rocks are you using?
Could you post a screenshot of the your connection dialog?
Do you have a check in Remember Me on the Sitecore login page?

**Comment by GonzoDark** [comment] 2016-08-04 07:59
I got the following error: "CS0246: The type or namespace name `__ReSharperSynthetic' could not be found. Are you missing a using directive or an assembly reference? "

And then found your solution to the problem here: https://visualstudiogallery.msdn.microsoft.com/44a26c88-83a7-46f6-903c-5c59bcd3d35b/view/Discussions/1

Where you said a solution to the issue could be to remove the lines from the browse.aspx file.
When I did that I got the exact same issue as lobrien2886.

I am using Sitecore.Rocks version 1.5.1.8 (and Sitecore.NET 8.1 (rev. 151207))

**Comment by PatrickdeBie** [comment] 2016-08-09 06:49
@JakobChristensen I had the same error (using Chrome) and I saw that the URL of the website was: <hostname>/?sc_itemid=xxxxxxxxxxxxxxxxx&sc_mode=preview (x being an ID).

After I manually added http:// at the beginning of the URL, the preview mode worked. So it became: http://<hostname>/?sc_itemid=xxxxxxxxxxxxxxxxx&sc_mode=preview

I'm using Sitecore Rocks 1.5.1.8 in Visual Studio 2015 and currently working on the new e-learning course from Sitecore.

**Comment by JakobChristensen** [comment] 2016-08-09 07:17
Hi Patrick

Seem to remember, that this may have been fixed in 2.0.0 - could you try the latest build

https://ci.appveyor.com/project/JakobChristensen/sitecore-rocks/build/2.0.30/artifacts

**Comment by PatrickdeBie** [comment] 2016-08-10 10:50
I'm not able to test this out momentarily, but I will in the future. If you don't hear anything from me, it works ;)

**Closed** 2016-12-02 08:40 UTC
